# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: React Casts
email: info@reactcasts.tech
description: > # this means to ignore newlines until "baseurl:"
  Screencasts / blog articles about all things React. From `create-react-app` to server-side-rendering,
  through React-Router and i18n, we'll cover it all!
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://reactcasts.tech" # the base hostname & protocol for your site
twitter_username: emilecantin
github_username: emilecantin

# Build settings
markdown: kramdown

